name: escape_parent_padding
description: A Flutter widget to let child widgets escape parent padding constraints, great for full-width layouts like horizontal ListViews.


version: 1.0.3
homepage: https://github.com/mosayyyed/escape_parent_padding

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

license: MIT
